---
- name: Add MongoDB apt key (Ubuntu)
  apt_key:  id=7F0CEB10
            keyserver=hkp://keyserver.ubuntu.com
  when: ansible_distribution == "Ubuntu"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB apt key (Debian)
  apt_key:  id=EA312927
            keyserver=hkp://keyserver.ubuntu.com
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB apt key (Debian Buster)
  apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB repository (Debian)
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main'
                  state=present
                  update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
  tags:
    - install
    - mongodb

- name: Add MongoDB repository (Debian Buster)
  apt_repository: repo='deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'
                  state=present
                  update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - install
    - mongodb    

- name: Disable kernel transparent huge-page defrag
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  copy:
    src: 99-thp-defrag.conf
    dest: /etc/sysfs.d/99-thp-defrag.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - mongodb
    - kernel

- name: Install MongoDB on Buster
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  apt:  
    pkg: [
      'mongodb-org',
      'mongodb-org-shell',
      'mongodb-org-server', 
      'mongodb-org-mongos'
    ]
    state: latest
  tags:
    - install
    - mongodb
    - deps  

- name: Install MongoDB
  when: ansible_distribution == "Ubuntu" or ( ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
  apt:  
    pkg: [
      'mongodb-org',
      'libsnappy1'
    ]
    state: latest
  tags:
    - install
    - mongodb
    - deps

- name: Install MongoDB
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
  apt:  
    pkg: [
      'mongodb',
    ]
    state: latest
  tags:
    - install
    - mongodb
    - deps  

- name: Install EPEL7
  yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - install

- name: Install MongoDB for CentOS
  when: ansible_distribution == "CentOS"
  yum:  
    pkg: [
      'mongodb-server'
    ]
    state: latest
  tags:
    - install
    - mongodb
    - deps

- name: set mongodb_service fact for CentOS
  when: ansible_distribution == "CentOS"
  set_fact:
    mongodb_service: "mongod"

- name: set mongodb_service fact for Ubuntu
  when: ansible_distribution == "Ubuntu"
  set_fact:
    mongodb_service: "mongodb"

- name: set mongodb_service fact for Debian
  when: ansible_distribution == "Debian"
  set_fact:
    mongodb_service: "mongod" 

- name: Make sure MongoDB is running
  service:  name={{ mongodb_service }}
            state=started
  tags:
    - install
    - mongodb
    - deps
    