---

- name: Set KernelCI services name fact for CentOS
  when: ansible_distribution == "CentOS"
  set_fact:
   redis_service_name: "redis"
   mongodb_service_name: "mongod"

- name: Set KernelCI services name fact for Debian/Ubuntu
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  set_fact:
   redis_service_name: "redis-server"
   mongodb_service_name: "mongodb"

- name: Make sure celery run directory exists
  file: path=/var/run/celery
        state=directory
        owner={{ app_user }}
        group={{ app_user }}
  tags:
    - init

- name: Install Upstart conf
  template: src=kernel-ci-backend.conf
            dest=/etc/init/{{ init_service }}.conf
            mode=0644
            owner=root
            group=root
  when: ansible_distribution == "Ubuntu"
  tags:
    - init
    - upstart

- name: Install kernelci systemd service
  template: src=kernelci-backend.service
            dest=/etc/systemd/system/{{ init_service }}.service
            mode=0644
            owner=root
            group=root
  when: ansible_distribution == "Debian" or ansible_distribution == "CentOS"
  notify:
    - reload-systemd
  tags:
    - init
    - systemd

- name: Enable kernelci systemd service
  command:  /bin/systemctl enable {{ init_service }}.service
            creates=/etc/systemd/system/multi-user.target.wants/{{ init_service }}.service
  when: ansible_distribution == "Debian" or ansible_distribution == "CentOS"
  tags:
    - init
    - systemd

- name: Install celery upstart configuration
  template: src=celery.conf
            dest=/etc/init/kernelci-celery.conf
            owner=root
            group=root
            mode=0644
  when: ansible_distribution == "Ubuntu"
  tags:
    - init
    - upstart

- name: Install celery systemd services
  template: src={{ item }}.service
            dest=/etc/systemd/system/{{ item }}.service
            owner=root
            group=root
            mode=0644
  when: ansible_distribution == "Debian" or ansible_distribution == "CentOS"
  with_items:
    - kernelci-celery
    - kernelci-celery-beat
  notify:
    - reload-systemd
  tags:
    - init
    - systemd

- name: Install celery beat upstart configuration
  template: src=kernelci-celery-beat.conf
            dest=/etc/init/kernelci-celery-beat.conf
            owner=root
            group=root
            mode=0644
  when: ansible_distribution == "Ubuntu"
  tags:
    - init
    - upstart

- name: Enable celery systemd service
  command:  /bin/systemctl enable {{ item }}.service
            creates=/etc/systemd/system/multi-user.target.wants/{{ item }}.service
  when: ansible_distribution == "Debian" or ansible_distribution == "CentOS"
  with_items:
    - kernelci-celery
    - kernelci-celery-beat
  notify:
    - reload-systemd
  tags:
    - init
    - systemd
